name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - develop
  

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    
    name: Build and Deploy Job
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"  # Aquí especificas la versión de Node.js que necesitas

      - name: Install dependencies
        run: npm install

      - name: Deploy Static Web App
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_FIELD_0B0BF4310 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "/" # App source code path
          output_location: "build" # Built app content directory - optional
